spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  application:
    name: "temario"
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8088

logging:
  level:
    org.hibernate.SQL: TRACE
    org.hibernate.type.descriptor.sql: TRACE